name: Code preparation.
run-name: ${{ github.actor }} is trying to push changes.
on:
  push:
    branches: [react]
  pull_request:
    branches: [react]
jobs:
  actions:
    name: Actions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Start formatting
        run: npm run format
      - name: Start linting
        run: npm run lint
      - name: Start type checking
        run: npm run type-checking
      - name: Start testing
        run: npm run test
        with:
          envkey_API_URL: https://example.com
          file_name: .env
