name: Code preparation.
run-name: ${{ github.actor }} is trying to push changes.
on:
  push:
    branches: react
jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    uses: actions/checkout@v4
    steps:
      - name: Install Dependencies
        run: npm install
      - name: Start formatting
        run: npm run format
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: npm install
      - name: Start linting
        run: npm run lint
  type-checking:
    name: Type checking
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: npm install
      - name: Start type checking
        run: npm run type-checking
